name       : perl-io-string
version    : 1.08
release    : 6
source     :
    - http://search.cpan.org/CPAN/authors/id/G/GA/GAAS/IO-String-1.08.tar.gz : 2a3f4ad8442d9070780e58ef43722d19d1ee21a803bf7c8206877a10482de5a0
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : IO::String is a class to read or write data from in-core strings.
description: |
    IO::String is an IO::File (and IO::Handle) compatible class that read or write data from in-core strings.  It is really just a simplification of what I needed from Eryq's IO-stringy modules.  As such IO::String is a replacement for IO::Scalar.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
